### ISSUE TITLE
500 error on demo site and site from the template

### ISSUE THREAD

**Issue by verythorough** [netlify-templates/nextjs-blog-theme#108]
Go to the demo site to reproduce:
https://bejamas-nextjs-blog.netlify.app/

Or [create a new site from the template](https://app.netlify.com/start-with-template) to reproduce in a new site.

cc @MarcL

**Comment by MarcL** [comment]
Thanks, @verythorough. Added the issue to the templates repo in the Netlify organisation so I can add it to a project board.
