### ISSUE TITLE
Add license for project

### ISSUE THREAD

**Issue by mroyme** [netlify-templates/nextjs-blog-theme#30]
From GitHub's [licensing](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license) page:

> ...without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license.

This practically makes the template unusable.

**Comment by maxcell** [comment]
Howdy @mroyme, while this project at the moment is without a license, this is by mistake not by intention. With that being said, I'll add an MIT license to the work.
