### ISSUE TITLE
Source code for the wizard

### ISSUE THREAD

**Issue by mcgear** [netlify-templates/nextjs-blog-theme#35]
I thought what you had done in the wizard with the theme selector was pretty cool, is the source code for that wizard somewhere to take a look at?

**Comment by maxcell** [comment]
Howdy @mcgear, we have the wizard valuable in this repository as well! It is under the `wizard` branch. We've not made sure that this branch is up-to-date with the rest of the project but you should be able to find the components here https://github.com/netlify-templates/nextjs-blog-theme/tree/wizard/components/wizard
