### ISSUE TITLE
Request for completeness

### ISSUE THREAD

**Issue by Pathsis** [netlify-templates/nextjs-blog-theme#54]
Request to add the following basic features: 

**archiving**, **paging**, **navigation**, **tagging** , **favicon**, and **searching**

This will make it a usable blog template. Very much anticipated!

**Comment by taty2010** [comment]
Hi @Pathsis, 

We appreciate you taking the time to send us this feature request. Currently, our main goal for the nextjs blog template is to provide users with a basic blog layout that allows for customization depending on the user's needs. 

Thank you!
