### ISSUE TITLE
Installing on ARM chip errors

### ISSUE THREAD

**Issue by brittneypostma** [netlify-templates/nextjs-blog-theme#73]
Tried cloning and running `npm install` and ran into an error regarding the ARM chip with the puppeteer package and the chromium binary.
```
npm ERR! code 1
npm ERR! path /Users/brittneypostma/Coding/abcs-of-netlify/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! The chromium binary is not available for arm64.
npm ERR! If you are on Ubuntu, you can install with: 
npm ERR! 
npm ERR!  sudo apt install chromium
npm ERR! 
npm ERR! 
npm ERR!  sudo apt install chromium-browser
npm ERR! 
npm ERR! /Users/brittneypostma/Coding/abcs-of-netlify/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:115
npm ERR!                     throw new Error();
npm ERR!                     ^
npm ERR! 
npm ERR! Error
npm ERR!     at /Users/brittneypostma/Coding/abcs-of-netlify/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:115:27
npm ERR!     at FSReqCallback.oncomplete (node:fs:198:21)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/brittneypostma/.npm/_logs/2022-08-25T00_48_26_875Z-debug-0.log
```

Just going to remove puppeteer for now.

**Comment by brittneypostma** [comment]
I was able to install after removing cypress and the netlify-plugin-cypress.

**Comment by maxcell** [comment]
Thank you for the report @brittneypostma! We've had intermittent issues with Cypress and the ARM. We can investigate what a possible solution might be. I believe the version of Cypress might not be as compatible as we expected. 

Could you also share what operating system and version you're running? Under "About this Mac"

**Comment by jzhzh** [comment]
Faced the same problem. My operating system is macOS Monterey 12.6.1 with M1 pro chip.
